version: "3.6"

services:
    api:
        image: api
        build:
            context: ../src
            dockerfile: "SuperLocker.Api/Dockerfile"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=secret#lock123
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/super_lock.pfx
        ports: 
            - "5000:80"
            - "5001:443"
        depends_on: 
            - rabbitmq
            - db
            - redis
        links: 
            - rabbitmq
            - db
            - redis
    auth:
        image: auth
        build:
            context: ../src
            dockerfile: "SuperLocker.Auth/Dockerfile"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=secret#lock123
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/super_lock.pfx
        ports: 
            - "5002:80"
            - "5003:443"
        depends_on: 
            - db
        links: 
            - db
        volumes: 
            - ./auth_cert:/https/
            
    db:
        image: mariadb
        hostname: db
        environment:
          MYSQL_ROOT_PASSWORD: rpass
        ports: 
            - 3306:3306
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
    
    redis:
        image: redis
        hostname: "redis"
        container_name: cache
        expose:
            - 6379
        ports: 
            - "6379:6379"
        volumes:
            - ./init:/docker-entrypoint-initdb.d

    rabbitmq:
        image: masstransit/rabbitmq:latest
        restart: always
        hostname: "rabbitmq"
        ports:
            - "5672:5672"
            - "15672:15672"
            - "15692:15692"
        healthcheck:
            timeout: 5s
            interval: 5s
            retries: 10
            test:
                - "CMD"
                - "rabbitmqctl"
                - "status"
