version: "3.6"

services:
    # api:
    #     image: api
    #     build:
    #         context: ../src
    #         dockerfile: "SuperLocker.Api/Dockerfile"
    #     network_mode: "host"

    db:
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: rpass
        ports: 
            - 3306:3306
    
    redis:
        image: redis
        container_name: cache
        expose:
            - 6379
        volumes:
          - ./init:/docker-entrypoint-initdb.d

    rabbitmq:
        image: masstransit/rabbitmq:latest
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
            - "15692:15692"
        healthcheck:
            timeout: 5s
            interval: 5s
            retries: 10
            test:
                - "CMD"
                - "rabbitmqctl"
                - "status"
